import numpy as np 

# np.array()

In [2]:
l = [1,2,3,4,5,6]

In [3]:
npa = np.array(l)

In [4]:
type(l),type(npa)

(list, numpy.ndarray)

In [5]:
npa.shape

(6,)

In [6]:
l.append('string')

In [7]:
npa = np.array(l)

In [8]:
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U11')

In [9]:
l1=[1,4,9,16]

In [10]:
l

[1, 2, 3, 4, 5, 6, 'string']

In [11]:
l+l1

[1, 2, 3, 4, 5, 6, 'string', 1, 4, 9, 16]

In [12]:
np.array(l+l1)

array(['1', '2', '3', '4', '5', '6', 'string', '1', '4', '9', '16'],
      dtype='<U11')

In [13]:
l = [(2,3),(4,6),(7,8)]

In [14]:
npa2d = np.array(l)

In [15]:
npa2d

array([[2, 3],
       [4, 6],
       [7, 8]])

In [16]:
npa2d.shape

(3, 2)

In [18]:
npa2d = np.array(l, dtype = 'float')

In [19]:
npa2d

array([[2., 3.],
       [4., 6.],
       [7., 8.]])

In [20]:
npa2d = npa2d.astype('str')

In [21]:
npa2d[0][0]

'2.0'

In [22]:
npa2d[0][0] +str(1)

'2.01'

# np.nan & np.inf

In [23]:
np.nan == np.nan

False

In [24]:
None == None

True

In [25]:
np.inf == np.inf 

True

In [28]:
npa2d =npa2d.astype('float')

In [29]:
npa2d = npa2d.astype('int')

In [30]:
npa2d

array([[2, 3],
       [4, 6],
       [7, 8]])

In [31]:
npa2d =npa2d.astype('float')

In [33]:
npa2d[0][0] = np.nan
npa2d[2][1] = np.inf

In [34]:
npa2d

array([[nan,  3.],
       [ 4.,  6.],
       [ 7., inf]])

In [36]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [37]:
np.isinf(npa2d)

array([[False, False],
       [False, False],
       [False,  True]])

In [38]:
flag = np.isnan(npa2d)  | np.isinf(npa2d)

In [39]:
flag

array([[ True, False],
       [False, False],
       [False,  True]])

In [40]:
npa2d[flag]

array([nan, inf])

# Statical operation

In [31]:
# mean, var, std, med

# Sequence, repetitions & random numbers

### arrange(), linspace(), random(), zeros(),  and ones()

In [36]:
import numpy as np
np.arange(1,5, dtype = 'float')

array([1., 2., 3., 4.])

In [37]:
 np.arange(1, 30, 3)   

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [38]:
np.linspace(1, 30, 3)

array([ 1. , 15.5, 30. ])

In [39]:
np.logspace(1, 50 ,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [40]:
np.zeros([1,5])

array([[0., 0., 0., 0., 0.]])

In [42]:
np.zeros([1 , 2, 3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [43]:
np.ones([10,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [44]:
 np.tile([1,2] , 3)

array([1, 2, 1, 2, 1, 2])

In [45]:
np.repeat([1,2],3)

array([1, 1, 1, 2, 2, 2])

In [46]:
np.random.rand(3,3)

array([[0.28686387, 0.07563443, 0.51272999],
       [0.09490027, 0.25652291, 0.01700189],
       [0.84409836, 0.5447682 , 0.53548279]])

In [47]:
np.random.randint(0,10,[3,3])

array([[0, 2, 0],
       [7, 3, 7],
       [4, 8, 3]])

In [50]:
np.random.seed(1)
np.random.randint(0,100,[3,3])

array([[37, 12, 72],
       [ 9, 75,  5],
       [79, 64, 16]])

# Where 

In [1]:
import numpy as np
arr = np.array([8,94,8,56,1,3,4,5,7])

In [2]:
arr

array([ 8, 94,  8, 56,  1,  3,  4,  5,  7])

In [3]:
np.where(arr>10)

(array([1, 3], dtype=int64),)

In [4]:
index = np.where(arr>10)
arr[index]

array([94, 56])

In [5]:
index = np.where(arr<10)
arr[index]

array([8, 8, 1, 3, 4, 5, 7])

In [6]:
index = np.where(arr==10)
arr[index]

array([], dtype=int32)

In [7]:
arr>10

array([False,  True, False,  True, False, False, False, False, False])

In [8]:
arr[arr>10]

array([94, 56])

In [9]:
arr.max()

94

In [10]:
arr.argmax()

1

In [11]:
arr.min()

1

In [12]:
arr.argmin()

4

In [14]:
arr[arr.argmin()]

1

In [16]:
arr[arr.argmin()]

1