# The Numpy array object

# NumPy Arrays 

#### Python objects
1) high -level number objects:integers, floating point
2) container list(costless insertions and append), distionaries(fast lookup)

### Numpy provides:

1) extension package to Python for multi-dimensional arrays
2) closer to hardware(efficiency)
3) designed for scientific computation(convenience)
4) Also kwown as array oriented coputing

In [1]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


#### why it is useful : Memory -efficient container that provides fast numerical operations.

In [2]:
# python lists
L = range(1000)
%timeit [i**2 for i in L]

536 µs ± 14.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
a= np.arange(1000)
%timeit a**2

2.87 µs ± 46.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 1 Creating arrays  

#### Manual Construction of arrays 

In [4]:
# 1-D
a = np.array([0,1,2,3])

a

array([0, 1, 2, 3])

In [5]:
# print dimensions
a.ndim

1

In [6]:
# shape
a.shape

(4,)

In [7]:
len(a)

4

In [8]:
# 2-D , 3-D ....
b = np.array([[0,1,2], [3,4,5]])

b

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
b.ndim

2

In [10]:
b.shape

(2, 3)

In [11]:
len(b) # returns the size of the first dimention

2

In [12]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])


c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
c.ndim

3

In [14]:
c.shape

(2, 2, 2)

### 1.2 functions for creating arrays 

In [15]:
#using arrange functions 
# arrange  is an array -valued version of the built-in Python range function 

a = np.arange(10) ## 0..... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a = np.linspace(0,1,6) # start  end , numberof points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
# using linspace
a = np.linspace(0,1,6) # start end , number of points 

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [18]:
# commmon arrays 


a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
d= np.eye(3,2) # number of rows , 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [20]:
# create array using diag functon

a = np.diag([1,2,3,4]) # construct a diagoanl array 

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.diag(a) # Extact diagoanl

array([1, 2, 3, 4])

In [22]:
# create  array using random

# create an array of the given shape and populate it with random samples from a uniform distribution over {0,1}

a = np.random.rand(4)

a

array([0.76201515, 0.46784477, 0.82459909, 0.32006878])

In [23]:
# a= np.random.randn(4)# Returns a sample (or samples) from  the "Standard normal" distribution .. "Gausian"
a

array([0.76201515, 0.46784477, 0.82459909, 0.32006878])

### note -

### For random samples from N(\mu,\sigma^2),use
##### sigma*np.random.randn(...) + mu

# 2. Basic  Data Types 


##### You may have  noticed that , in some instances ,array elements are displayed  with  a  trailing dot (e.g .2. vs 2) . This is due to a diference in the data- type used .

In [24]:
a= np.arange(10)
a.dtype

dtype('int32')

In [27]:
# You can explicitly specity which data -type you want:
a = np.arange(10, dtype = 'float64')

a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
# the default data type is float for zeros and  ones function

a = np.zeros((3,3))

print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

##### other datatypes 

In [30]:
d= np.array([1+2j, 2+4j]) # Complex datatype

print(d.dtype)


complex128


In [31]:
b= np.array([True, False, True,False ]) # Boolean datatype

print(b.dtype)

bool


In [32]:
s= np.array(['Ram', 'Rahul', 'Rahim'])

s.dtype

dtype('<U5')

##### Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

For more details

https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html



#  3 . Indexing & Slicing 

###### 3.1  Indexing 

The items of an array can be accessed and assigned to the same way as other Python sequences(e.g lists)

In [33]:
a= np.arange(10)

print(a[5]) # indices begins at 0 like other python sequences (and c/c++)

5


In [34]:
# for multidimensional arrays , indxes are tuples of integers:
a = np.diag([1,2,3])
print(a[2,2])

3


In [35]:
a[2,1] = 5 # assigning value 
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

#### 3.2 Slicing

In [37]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
a[1:8:2] # [start endindex(exclusive) : step]

array([1, 3, 5, 7])

In [39]:
# we can also combine assignment ans slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [40]:
b= np.arange(5)
a[5:] = b[:: -1] # assigning

a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

# 4 Copies and Views 

A slicing operation creates a view on the original array, which is just a way of accessing array data . Thus the original array is not copied  in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

#### When modifying the view, the original array is modified as well :

In [41]:
a= np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [43]:
np.shares_memory(a,b)

True

In [44]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [45]:
a  # eventhough we modified b , it updated 'a' because both shares same meoory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
a = np.arange(10)
c = a[::2].copy()  # force a copy 
c

array([0, 2, 4, 6, 8])

In [47]:
np.shares_memory(a,c)

False

In [48]:
c[0] = 10 

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5 Fancy Indexing 

#### NumPy array can be indexed with slices, but also with boolean or integer arrays (masks). This  method  is called fancy  indexing .It creates copies not views.

#### Using Boolean Mask

In [49]:
a = np.random.randint(0,20,15)

a

array([13, 16, 19,  6, 11, 18,  8, 13,  2,  3,  1,  4,  6, 11, 11])

In [50]:
mask  = (a % 2 == 0)

In [51]:
extract_from_a = a[mask]
extract_from_a

array([16,  6, 18,  8,  2,  4,  6])

### Indexing with a mask can be very useful to assign a new value to sub-array: 

In [52]:
a[mask] = -1

a

array([13, -1, 19, -1, 11, -1, -1, 13, -1,  3,  1, -1, -1, 11, 11])

### Indexing with an array of integers  

In [54]:
a = np.arange( 0,100,10)

a 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
# indexing ca nbe done with array of integers ,where the same index is repeated several time:
a [[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [56]:
# New vlaues can be assignd 

a [[9,7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [1]:
import numpy as  np

# Elementwise Operations  

##### 1 Basic Operations  with Scalars 

In [3]:
a = np.array([1,2,3,4]) # Create an array 
a+1

array([2, 3, 4, 5])

In [4]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

##### All Arithmetic operates elementwise

In [5]:
b = np.ones(4) + 1
a-b

array([-1.,  0.,  1.,  2.])

In [6]:
a*b

array([2., 4., 6., 8.])

In [7]:
# Matrix  multiplication

c = np.diag([1,2,3,4])

print(c*c)
print("******************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
******************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


##### Comparisions 

In [8]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b

array([False,  True, False,  True])

In [9]:
a>b

array([False, False,  True, False])

In [10]:
# array wise comparisions 
a = np.array([1,2,3,4])

b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [11]:
np.array_equal(a,c)

True

### Logical Operations 

In [13]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)

np.logical_or(a,b)


array([ True,  True,  True, False])

In [14]:
np.logical_and(a,b)

array([ True, False, False, False])

##### Transendental Functions 

In [16]:
a = np.arange(5)

np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [17]:
np.log(a)

<ipython-input-17-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [18]:
np.exp(a) #  evaluates e^x for each element in a given input


array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

##### Shape Mismatch 

In [22]:
a = np.arange(4)

a + np.array([1, 2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Basic Reductions 
###### Computing Sums 

In [23]:
x = np.array([1,2,3,4])
np.sum(x)

10

In [25]:
# sum by rows and by columns

x = np.array([[1,1],[2,2]])

x

array([[1, 1],
       [2, 2]])

In [26]:
x.sum(axis=0) # columns first dimension

array([3, 3])

In [27]:
x.sum(axis=1) # rows (second dimension)

array([2, 4])

#### Other reductions 

In [28]:
x = np.array([1,2,3])
x.min()

1

In [29]:
x.argmax() # index of maximum element

2

#### Logical Operations

In [30]:
np.all([True, True, False])

False

In [31]:
np.any([True, False, False])

True

In [32]:
#note: can be used for array comparisions

a = np.zeros((50,50))
np.any(a != 0 )

False

In [33]:
np.all(a == a)

True

In [34]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a<= b) & (b <= c )).all()


True

##### Statistics

In [38]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [39]:
np.median(x)

1.5

In [40]:
np.median(y, axis=-1) # last axis 

array([2., 5.])

In [41]:
x.std() # full population standard dev

0.82915619758885

#### Example:

###### Data in populations.text describes the populations of hares and lynxes(and carrots) in northern Canada duriung 20 years.

# Broadcasting
Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size. Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

In [48]:
a = np.tile(np.arange(0,40,10),(3,1))

print(a)

print("************")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [49]:
b = np.array([0,1,2])
b

array([0, 1, 2])

In [50]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [52]:
a = np.arange(0,40,10)
a.shape

(4,)

In [54]:
 a = a[:, np.newaxis] # adds a new axis -> 2D array
    
a.shape

(4, 1, 1)

In [55]:
a

array([[[ 0]],

       [[10]],

       [[20]],

       [[30]]])

In [56]:
a+b

array([[[ 0,  1,  2]],

       [[10, 11, 12]],

       [[20, 21, 22]],

       [[30, 31, 32]]])

# Array Shape Manipulation 

##### Flattening

In [57]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel() # Return a  contiguous flattened array . A 1D array, containing  the elements of input, is returned. A copy is made only if needed.

array([1, 2, 3, 4, 5, 6])

In [58]:
a.T # Transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

##### Reshaping

The inverse operation to flattening:

In [60]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [63]:
b = b.ravel()
b


array([1, 2, 3, 4, 5, 6])

In [64]:
b = b.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

#### Note and Beware; reshape May also return a copy !:



In [66]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

###### Adding a Dimension

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [67]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [68]:
z[:, np.newaxis]

array([[1],
       [2],
       [3]])

###### Dimension Shuffling 

In [72]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [73]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [74]:
a[0,2,1]

5

#### Reisizing

In [75]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

######## However it must not be referred to somewhere else:


In [76]:
b = a
a.resize((4,))

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

##### Sorting  data

In [77]:
#  sorting along an axis:
a = np.array([[5,4,6], [2,3,2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [78]:
#in - place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [79]:
# sorting with fancy indexing 
a = np.array([4,3,1,2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [80]:
a[j]

array([1, 2, 3, 4])