In [1]:
import numpy as np

In [3]:
a  = [1,2,3, "hi"]

In [4]:
a

[1, 2, 3, 'hi']

In [5]:
a = [1,2,3]

In [6]:
b = [5,6,7]

In [7]:
a+b

[1, 2, 3, 5, 6, 7]

In [8]:
c = np.array(a)
d = np.array(b)

In [9]:
c

array([1, 2, 3])

In [10]:
d

array([5, 6, 7])

In [11]:
c+d

array([ 6,  8, 10])

In [13]:
b = np.array(a)

In [14]:
b

array([1, 2, 3])

In [15]:
b.ndim

1

In [16]:
c = np.array([[1,2,3],[2,3,4]])

In [17]:
c

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
c.shape

(2, 3)

In [19]:
c.dtype

dtype('int64')

In [20]:
c.size

6

In [21]:
a = range(100)

In [22]:
import sys

In [23]:
print(sys.getsizeof(5)*len(a))

2800


In [24]:
e = np.arange(100)

In [26]:
print(e.size*e.itemsize)

800


In [27]:
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
a = np.arange(100)

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
a = np.arange(3,10)

In [31]:
a

array([3, 4, 5, 6, 7, 8, 9])

In [33]:
a = np.arange(3,11).reshape(2,4)

In [34]:
a

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [35]:
b = np.arange(3,11).reshape(2,2,2)

In [36]:
b

array([[[ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10]]])

In [38]:
a = np.array([[1.2,3.4,5.6], [2.3,4.5,6.7]])

In [39]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [40]:
type(a)

numpy.ndarray

In [41]:
a.dtype

dtype('float64')

In [42]:
b = np.array([[2,3,4],[7,8,9]])

In [43]:
b

array([[2, 3, 4],
       [7, 8, 9]])

In [44]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [45]:
a+b

array([[ 3.2,  6.4,  9.6],
       [ 9.3, 12.5, 15.7]])

In [46]:
a*b

array([[ 2.4, 10.2, 22.4],
       [16.1, 36. , 60.3]])

In [47]:
a/b

array([[0.6       , 1.13333333, 1.4       ],
       [0.32857143, 0.5625    , 0.74444444]])

In [48]:
c = np.array([[3,5], [5,6]])

In [49]:
c

array([[3, 5],
       [5, 6]])

In [50]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [51]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [52]:
a.shape

(2, 3)

In [53]:
c.shape

(2, 2)

In [54]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [55]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [56]:
np.linspace(2,5,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [57]:
np.linspace(2,20, 4)

array([ 2.,  8., 14., 20.])

In [58]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [59]:
a.max()

6.7

In [60]:
a.min()

1.2

In [62]:
a.argmax()

5

In [63]:
a.argmin()

0

In [64]:
a.tolist()

[[1.2, 3.4, 5.6], [2.3, 4.5, 6.7]]

In [65]:
a

array([[1.2, 3.4, 5.6],
       [2.3, 4.5, 6.7]])

In [66]:
a.size

6

In [67]:
np.max(a)

6.7

In [68]:
a+b

array([[ 3.2,  6.4,  9.6],
       [ 9.3, 12.5, 15.7]])

In [69]:
a = np.arange(10,20)

In [70]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
a>15

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [72]:
a[a>15]

array([16, 17, 18, 19])

In [73]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [74]:
a+100

array([110, 111, 112, 113, 114, 115, 116, 117, 118, 119])

In [75]:
a*8

array([ 80,  88,  96, 104, 112, 120, 128, 136, 144, 152])

In [76]:
b

array([[2, 3, 4],
       [7, 8, 9]])

In [77]:
b<=5

array([[ True,  True,  True],
       [False, False, False]])

In [78]:
b[b<=5]

array([2, 3, 4])

In [79]:
b

array([[2, 3, 4],
       [7, 8, 9]])

In [80]:
np.sum(b)

33

In [81]:
np.mean(b)

5.5

In [82]:
np.median(b)

5.5

In [83]:
b.mean()

5.5

In [84]:
a = [1,2,3,4]

In [86]:
b

array([[2, 3, 4],
       [7, 8, 9]])

In [87]:
b[2:3]

array([], shape=(0, 3), dtype=int64)

In [88]:
b[1:2]

array([[7, 8, 9]])

In [94]:
c = np.arange(2,10).reshape(4,2)

In [95]:
c

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
c[2,4]

IndexError: index 4 is out of bounds for axis 1 with size 2

In [104]:
c = np.arange(2,14).reshape(4,3)

In [105]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [106]:
c[2:4]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [107]:
c[2:6]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [108]:
c[2:]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [109]:
c[:3]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [110]:
c[:,:]

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [111]:
c[,2:3]

SyntaxError: invalid syntax (<ipython-input-111-190687d46cfb>, line 1)

In [112]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [113]:
c[2:,:3]

array([[ 8,  9, 10],
       [11, 12, 13]])

In [114]:
c[3:,1:]

array([[12, 13]])

In [115]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [116]:
c.remove(9)

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [118]:
d = c.ravel()

In [119]:
d.remove(9)

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [120]:
c.remove([8,9,10])

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [2]:
import numpy as np
a = np.arange(2,14).reshape(4,3)

In [3]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [5]:
d = np.delete(a,5)

In [7]:
d.reshape()

array([[ 2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13]])

In [8]:
np.delete(a, 1, axis=0)

array([[ 2,  3,  4],
       [ 8,  9, 10],
       [11, 12, 13]])

In [9]:
np.delete(a, 1, axis=1)

array([[ 2,  4],
       [ 5,  7],
       [ 8, 10],
       [11, 13]])

###  Copy and view

In [11]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [12]:
b = a.copy()

In [13]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [14]:
b[3] = 10

In [15]:
b

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [10, 10, 10]])

In [16]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [17]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [18]:
c = a.view()

In [19]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [20]:
c[3] = 10

In [21]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [10, 10, 10]])

In [22]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [10, 10, 10]])

In [23]:
a = 5

In [24]:
b = 5

In [25]:
a

5

In [27]:
b

5

In [28]:
a

5

In [31]:
a = np.array([1,2,3,4,5])

In [32]:
a

array([1, 2, 3, 4, 5])

In [33]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [34]:
b = np.array([1.2, 2.6, 5.7, 3.2])

In [35]:
b

array([1.2, 2.6, 5.7, 3.2])

In [36]:
np.floor(b)

array([1., 2., 5., 3.])

In [37]:
np.ceil(b)

array([2., 3., 6., 4.])

In [38]:
np.exp(a)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [39]:
a

array([1, 2, 3, 4, 5])

In [40]:
a = np.arange(2,14).reshape(4,3)

In [41]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [44]:
b = a.flatten()

In [43]:
a.shape

(4, 3)

In [45]:
b.shape

(12,)

In [46]:
b.ndim

1

In [47]:
a.ndim

2

In [48]:
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [50]:
c = a.ravel()

In [51]:
c

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [52]:
c[3] = 20

In [53]:
c

array([ 2,  3,  4, 20,  6,  7,  8,  9, 10, 11, 12, 13])

In [54]:
a

array([[ 2,  3,  4],
       [20,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [55]:
a

array([[ 2,  3,  4],
       [20,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [56]:
d = a.flatten()

In [57]:
d

array([ 2,  3,  4, 20,  6,  7,  8,  9, 10, 11, 12, 13])

In [58]:
d[5] = 50

In [59]:
d

array([ 2,  3,  4, 20,  6, 50,  8,  9, 10, 11, 12, 13])

In [60]:
a

array([[ 2,  3,  4],
       [20,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [61]:
a

array([[ 2,  3,  4],
       [20,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [63]:
a.shape

(4, 3)

In [64]:
a.reshape(2,6)

array([[ 2,  3,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [65]:
a.reshape(3,4)

array([[ 2,  3,  4, 20],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [66]:
a

array([[ 2,  3,  4],
       [20,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [69]:
e = a.resize(2,6)

In [71]:
a

array([[ 2,  3,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [72]:
a

array([[ 2,  3,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [73]:
b = np.arange(12).reshape(2,6)

In [74]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [75]:
### Stacking

In [78]:
np.hstack((a,b))

array([[ 2,  3,  4, 20,  6,  7,  0,  1,  2,  3,  4,  5],
       [ 8,  9, 10, 11, 12, 13,  6,  7,  8,  9, 10, 11]])

In [79]:
np.vstack((a,b))

array([[ 2,  3,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [80]:
b = np.arange(24).reshape(4,6)

In [81]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [82]:
np.split(b,2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [90]:
e,d,r,t = np.split(b,4)

In [85]:
a

array([[ 2,  3,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [86]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [88]:
a = np.array([[1,2],[3,4]])

In [96]:
a

array([[1, 2],
       [3, 4]])

In [89]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [91]:
e

array([[0, 1, 2, 3, 4, 5]])

In [92]:
d

array([[ 6,  7,  8,  9, 10, 11]])

In [93]:
d

array([[ 6,  7,  8,  9, 10, 11]])

In [94]:
d>8

array([[False, False, False,  True,  True,  True]])

In [95]:
d[d>8]

array([ 9, 10, 11])

In [110]:
d = np.arange(1,17).reshape(4,4)
np.linalg.inv(d)

LinAlgError: Singular matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [115]:
e = np.arange(1,10).reshape(3,3)
np.linalg.inv(e)

LinAlgError: Singular matrix

In [112]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
np.linalg.inv(d)

LinAlgError: Singular matrix

In [116]:
a

array([[1, 2],
       [3, 4]])

In [117]:
b = np.array([5,6])

In [118]:
b

array([5, 6])

In [119]:
a+b

array([[ 6,  8],
       [ 8, 10]])

In [120]:
a

array([[1, 2],
       [3, 4]])

In [121]:
a*5

array([[ 5, 10],
       [15, 20]])

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
c

array([ 2,  3,  4, 20,  6,  7,  8,  9, 10, 11, 12, 13])

In [124]:
a+c

ValueError: operands could not be broadcast together with shapes (2,2) (12,) 

In [125]:
a

array([[1, 2],
       [3, 4]])

a+10

In [127]:
b

array([5, 6])

In [128]:
b.shape

(2,)

In [129]:
a

array([[1, 2],
       [3, 4]])

In [130]:
c

array([ 2,  3,  4, 20,  6,  7,  8,  9, 10, 11, 12, 13])

In [131]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
np.linalg.inv(d)

LinAlgError: Singular matrix

In [133]:
b

array([5, 6])

In [134]:
c = np.arange(1,13).reshape(3,4)

In [135]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [136]:
c.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [137]:
c.trace()

18

In [138]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])